---
PRINT_ALPACA: false
EMAIL_REPORTER: false
APPLY_FIXES: all

# Lint specifig settings
ENABLE: [BASH, MARKDOWN, YAML, ACTION, DOCKERFILE, COPYPASTE, CREDENTIALS]
DISABLE_LINTERS: [DOCKERFILE_DOCKERFILELINT]

ACTION_ACTIONLINT_ARGUMENTS: -ignore 'property "json" is not defined'
BASH_SHFMT_ARGUMENTS: -i 2
BASH_SHFMT_FILE_EXTENSIONS: [.sh, .bash, .bats]
BASH_SHELLCHECK_FILE_EXTENSIONS: [.sh, .bash, .bats]
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: src/scripts
COPYPASTE_JSCPD_ARGUMENTS: --ignore "test/lib,report,LICENSES"
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3006"
