---
variables:
  DISABLE_SHALLOW_CLONE:
    value: "false"
    description: |
      If 'true', the full history of the project is cloned.
      This option works only if VCS_TYPE is 'git'.
      Check this option only if you know that it is required for your scan.
      Will fail if not ORT_DISABLE_DOWNLOADER is set to false
      (the default CI checkout is used otherwise).

  FAIL_ON_OUTDATED_NOTICE_FILE:
    value: "false"
    description: |
      If 'true', the scan will be considered as failed if generated NOTICE file differs from the one in your repository.

  NOTICE_FILE:
    value: FOSS_NOTICE
    description: |
      Path to open source attribution document relative to the VCS root.
      If empty 'FOSS_NOTICE' is used as default.

  ORT_ALLOW_DYNAMIC_VERSIONS:
    value: "false"
    description: |
      Set to 'true' only if dynamic dependency versions are allowed (note version ranges specified for dependencies may cause unstable results).
      This field applies only to package managers that support lock files, e.g. NPM.

  ORT_CONFIG_REPO_URL:
    value: https://github.com/oss-review-toolkit/ort-config.git
    description: |
      Url to a git repo containing configuration, defaults to the ORT CONFIG repo.

  ORT_CONFIG_REVISION:
    value: main
    description: |
      The Git revision of the ORT configuration repository to use.

  ORT_DISABLE_ADVISOR:
    value: "true"
    description: |
      If 'true', ORT's advisor will not run (no security vulnerability checks).

  ORT_DISABLE_DOWNLOADER:
    value: "true"
    description: |
      If 'true', ORT's downloader will not run (no project download by ort itself).
      For example, GitLab/GitHub has per default already cloned your project, so you don't need
      to use ORT.

  ORT_DISABLE_EVALUATOR:
    value: "true"
    description: |
      If 'true', ORT's evaluator will not run (no policy checks).

  ORT_DISABLE_SCANNER:
    value: "true"
    description: |
      If 'true', ORT's scanner will not run (no copyright holders and licenses scan).

  ORT_LOG_LEVEL:
    value: info
    description: |
      'debug' to see additional debug output to help tracking down errors.
      'performance' for less logs.
      'info' as default.

  ORT_USE_DEV_DB:
    value: "false"
    description: |
      If 'true', download/upload scanned results from/to development database.

  ORT_URL:
    value: https://github.com/oss-review-toolkit/ort.git
    description: |
      Where to get the ORT code base.

  ORT_DOCKER_IMAGE:
    value: ""
    description: |
      The CI Docker ORT Image to use

  ORT_CONFIG_FILE:
    value: ""
    description: |
      Path to repository configuration file relative to the VCS root.
      If empty '.ort.yml' is used as default.

  PROJECT_DIR:
    value: "./"
    description: |
      Path to actual cloned project folder in the CI-pipe.
      Defaults to 'project'.

  RUNNER_TAG:
    value: k8s
    description: |
      A runner tag for the gitlab runner.

  VCS_PATH:
    value: ""
    description: |
      Leave this field empty unless one of the following special cases applies:
        project VCS_TYPE is git-repo - specify path to repo manifest file (e.g. olympia.xml, note VCS_URL must point to a manifest repository)
        you require sparse checkout - specify repository sub-path to download and scan (e.g. projects/gradle/, note sparse checkout is
        possible only for VCS_TYPE git, mercurial or subversion).

  # ----ORT DOWNLOADER OPTIONS - set this if ORT_DISABLE_DOWNLOADER=false

  SW_NAME:
    value: ""
    description: |
      Name of project, product or component to be scanned.
      By default the name of the repository is used as shown in its clone URL.
      Only used if ORT_DISABLE_DOWNLOADER is set to false.

  SW_VERSION:
    value: ""
    description: |
      Project version number or release name (use the version from package metadata, not VCS revision).
      By default, the Git Short SHA is used.
      Only used if ORT_DISABLE_DOWNLOADER is set to false.

  VCS_REVISION:
    value: ""
    description: |
      SHA1 or tag to scan (not branch names, because they can move).
      If VCS_TYPE is 'git-repo':
        SHA1 must be unabbreviated, tag names must be prefixed with 'refs/tags/'.
      By default, the Git Commit SHA is used.
      Only used if ORT_DISABLE_DOWNLOADER is set to false.

  VCS_TYPE:
    value: git
    description: |
      Identifier of the project version control system (git, git-repo, mercurial or subversion).
      Only used if ORT_DISABLE_DOWNLOADER is set to false.

  VCS_URL:
    value: ""
    description: |
      VCS URL (clone URL) of the project to scan, use only when URL is not correctly detected.
      Only used if ORT_DISABLE_DOWNLOADER is set to false.

  ORT_CI_ACTION_REPO:
    value: https://github.com/janderssonse/ort-ci-action
    description: |
      Script repo. For the main CI script.

  ORT_CI_ACTION_BRANCH:
    value: main
    description: |
      Script repo, dev help. Check out another branch.

ort-scan:
  stage: ort-scan
  image:
    name: "$ORT_DOCKER_IMAGE"
    entrypoint: [""]
  tags:
    - "$RUNNER_TAG"
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
      - cache/.m2/repository
      - cache/.go/pkg/mod
      - cache/pip
      - cache/.gradle
      - cache/yarn
      - cache/node_modules
      - cache/ivy2/cache
      - cache/sbt
  before_script:
    - export ORT_BASE_SCRIPTS_DIR=$(mktemp -d)
    - git clone -q --depth 1 --branch "$ORT_CI_ACTION_BRANCH" "$ORT_CI_ACTION_REPO" "$ORT_BASE_SCRIPTS_DIR"
    - export ORT_SCRIPTS_DIR="${ORT_BASE_SCRIPTS_DIR}/src/scripts"
    - export ORT_CLI_CONFIG_TMPL="${ORT_BASE_SCRIPTS_DIR}/templates/ort.conf.tmpl"

  script:
    - $ORT_BASE_SCRIPTS_DIR/src/ort-ci-main.sh main

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

  artifacts:
    when: always
    paths:
      - ort-results
      - metadata.json
