---
name: Commitlint
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install -g @commitlint/config-conventional @commitlint/cli

      - name: Commitlint Pull Requests
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Commitlint Master/Main
        if: github.ref_name == 'master' || github.ref_name == 'main'
        run: commitlint --from HEAD~1 --to HEAD --verbose
