---
name: Build/Publish ort-ci-action image
# Builds and base image from the ORT repo
# Uses base image to build the CI image with Dockerfile from the ORT GitLab CI project
# Uses ci image as a result for the action image
#
on: [workflow_call, workflow_dispatch] # yamllint disable-line rule:truthy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_CI: ort-ci-base
  IMAGE_NAME_ACTION: ort-ci-action

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: github.ref_name == 'wip/refactor' || github.ref_name == 'main'
    steps:
      - name: Checkout Actions repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Checkout ORT repo
        uses: actions/checkout@v3
        with:
          repository: oss-review-toolkit/ort
          path: ort

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Finally build the Action image
      - name: Extract metadata (tags, labels) for ort action image
        id: ort_action_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_ACTION }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{branch}},priority=1,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=tag,priority=2
            type=raw,value=${{ env.IMAGE_NAME_ACTION }}-{{branch}}-{{date 'YYYYMMDD'}}-{{sha}},priority=31,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{ env.IMAGE_NAME_ACTION }}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}},priority=32, enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}
            type=sha
            type=sha,format=long

      - name: Build and push ort action image
        id: docker_action_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.ort_action_meta.outputs.tags }}
          labels: ${{ steps.ort_action_meta.outputs.labels }}
          build-args: |
            BASEIMAGE=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_CI }}
